services:
  linkpulse-api:
    build: ./linkpulse
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  linkpulse-worker:
    build: ./linkpulse-worker
    env_file:
      - ./.env
    depends_on:
      - linkpulse-api

  linkpulse-dashboard:
    build: ./linkpulse-dashboard
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api/analytics
    depends_on:
      - linkpulse-api